// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmlMidCnd6oSTT6Xt1i1KAi0Xa87aCErs',
    appId: '1:377468552139:web:d02d987c5d163baf4c2c4e',
    messagingSenderId: '377468552139',
    projectId: 'flutterproject-ee373',
    authDomain: 'flutterproject-ee373.firebaseapp.com',
    databaseURL: 'https://flutterproject-ee373-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-ee373.firebasestorage.app',
    measurementId: 'G-RQK0VTTS4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcJWRIeLDlZJx9pmC7yDDi7j9I5M4Lqbk',
    appId: '1:377468552139:android:62148c84a3af5a2e4c2c4e',
    messagingSenderId: '377468552139',
    projectId: 'flutterproject-ee373',
    databaseURL: 'https://flutterproject-ee373-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-ee373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYBBX1OaJI5uW9_y_vFQReuID0YbvFOc4',
    appId: '1:377468552139:ios:c1764f3bccd606cf4c2c4e',
    messagingSenderId: '377468552139',
    projectId: 'flutterproject-ee373',
    databaseURL: 'https://flutterproject-ee373-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-ee373.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYBBX1OaJI5uW9_y_vFQReuID0YbvFOc4',
    appId: '1:377468552139:ios:c1764f3bccd606cf4c2c4e',
    messagingSenderId: '377468552139',
    projectId: 'flutterproject-ee373',
    databaseURL: 'https://flutterproject-ee373-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-ee373.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmlMidCnd6oSTT6Xt1i1KAi0Xa87aCErs',
    appId: '1:377468552139:web:156fa7f5e4a607eb4c2c4e',
    messagingSenderId: '377468552139',
    projectId: 'flutterproject-ee373',
    authDomain: 'flutterproject-ee373.firebaseapp.com',
    databaseURL: 'https://flutterproject-ee373-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-ee373.firebasestorage.app',
    measurementId: 'G-T9SETNGBRG',
  );

}